### ISSUE TITLE
Window size too small at start up. Remember window size.

### ISSUE THREAD

**Issue by HubKing** [pedrolcl/dmidiplayer#17]
Plasma 6, Wayland, fractional scaling. The app's window is always this size when launched.

![image](https://github.com/pedrolcl/dmidiplayer/assets/10900489/0d751f0c-4003-4b90-862b-8ed17d8d130f)

And it doesn't remember the window size, so i have to resize it every single time I start it.

It has to either set the initial size properly, or remember the window size.

**Comment by pedrolcl** [comment]
First of all: your report lacks fundamental information, like if you are using X11 or Wayland. Please run the `fastfetch` or `neotech` or `screenfetch` scripts (or an equivalent alternative) and post the reported details here. Thanks.

Second:  dmidiplayer stores and restores the window size and position since the first day. It honors [Qt's best practice](https://doc.qt.io/qt-6/restoring-geometry.html) which has always worked well in MS-Windows, MacOS and Unix/X11.

But you are probably using Wayland, and the Wayland morons have decided that they don't want to allow this practice, so you are out of luck. Please report your frustration to them, and don't blame me. Or alternatively, switch to X11.

**Comment by pedrolcl** [comment]
See also: 
https://bugreports.qt.io/browse/QTBUG-80612
https://gist.github.com/probonopd/9feb7c20257af5dd915e3a9f2d1f2277

**Comment by HubKing** [comment]
You forgot to notice that I had mentioned "Wayland" at the beginning. Anyway, I know Wayland does not support setting window location, but it allows setting the window size. The linked issue is for Gnome. I had also mentioned that I am using Plasma 6, and setting the window size in my PySide6 app works, so it should not be a problem of Wayland or QT6.

Seems like the app has some sort of bug of handling multi-monitors with different scaling values. On my laptop, which is similar set-up as the desktop, the initial size was correct, and the laptop has only one screen. The desktop has 2, so I tried disabling one monitor and then launched Dmid. The initial size was correct.

If Dmid is storing/restoring window size, I think it is also a bug that restoring does not work under Wayland.

**Comment by pedrolcl** [comment]
> Seems like the app has some sort of bug of handling multi-monitors with different scaling values.

You forgot to mention in your original report that you are using several monitors and the issue  is only relevant in that case.  So, to me the initial placement of the window is relevant in that case, because Qt uses a single coordinate space for all monitors when you don't use replication mode.

Anyway, you seem to be sure about where is the bug, and you say that you know how to fix it. Very well, then I await your patch or pull request. But please don't break other platforms in the process (Gnome, Windows, macOS, ...)
